In [1]:
import numpy as np

In [19]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

sum_matrix=A+B
elementwise_product=A*B
Dot_product=np.dot(A,B)
Matrix_Multiplication=A@B

print("Sum of the Matrix:\n",sum_matrix)
print("Element wise product:\n",elementwise_product)
print("Dot product:\n",Dot_product)
print("Matrix Multiplication:\n",Matrix_Multiplication)

Sum of the Matrix:
 [[ 6  8]
 [10 12]]
Element wise product:
 [[ 5 12]
 [21 32]]
Dot product:
 [[19 22]
 [43 50]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
